// Generated by Wrangler on Fri Aug 16 2024 18:58:47 GMT+0200 (Ora legale dell’Europa centrale)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	DB: D1Database;
}
