// Generated by Wrangler on Wed Aug 21 2024 15:14:08 GMT+0200 (Ora legale dell’Europa centrale)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	SEASON_ID: "264681";
	DB: D1Database;
}
