#:schema node_modules/wrangler/config-schema.json
name = "ms-bot-dashboard"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "default"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "8a298455-ac11-4e0c-b160-4db807cf3572"

[vars]
SEASON_ID = "264681"

[[kv_namespaces]]
binding = "KV"
id = "0f620c8b0c9e4b0786b894509f82e5d9"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
