import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "tailwindcss/tailwind.css";
import "./globals.css";

const font = Roboto({ subsets: ["latin"], weight: "400", display: "swap" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${font.className} min-h-screen text-white bg-zinc-800`}>
				{children}
			</body>
		</html>
	);
}
